cp grid_data17_periodB.cxx grid_data17_periodC.cxx
cp grid_data17_periodB.cxx grid_data17_periodD.cxx
cp grid_data17_periodB.cxx grid_data17_periodE.cxx
cp grid_data17_periodB.cxx grid_data17_periodF.cxx
cp grid_data17_periodB.cxx grid_data17_periodH.cxx
cp grid_data17_periodB.cxx grid_data17_periodI.cxx
cp grid_data17_periodB.cxx grid_data17_periodK.cxx
